PROGRAM biggest
IMPLICIT NONE

REAL A, B, TOL
PRINT*, 'Input first number'
READ*, A
PRINT*, 'Input second number'
READ*, B
TOL=0.00001
IF( ABS(A-B)<TOL )THEN
   PRINT*, 'NUMBERS ARE EQUAL'
ELSE IF (A > B) THEN
   PRINT*, 'LARGEST NUMBER IS ', A
ELSE IF (B < A) THEN
   PRINT*, 'LARGEST NUMBER IS ', B
ELSE
   PRINT*, 'SOMETHING WENT WRONG HERE'
END IF

END PROGRAM biggest
